name: CI Pipeline

on:
  push:
    branches: [main, develop, quality-engineering-project]
  pull_request:
    branches: [main, develop, quality-engineering-project]

jobs:
  backend-tests:
    name: Backend Tests & Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Run linter
        run: npm run lint --if-present
        continue-on-error: true

      - name: Run tests
        run: npm test --if-present
        continue-on-error: true

      - name: Check server startup
        run: |
          timeout 10s npm start || true
        continue-on-error: true

  frontend-build:
    name: Frontend Build & Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Run linter
        run: npm run lint --if-present
        continue-on-error: true

      - name: Build application
        run: npm run build --if-present

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: frontend-build
          path: frontend/build

  cypress-e2e:
    name: Cypress E2E Tests - Admin Module
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    
    strategy:
      fail-fast: false
      matrix:
        spec:
          - cypress/e2e/admin/auth.cy.js
          - cypress/e2e/admin/dashboard.cy.js
          - cypress/e2e/admin/class.cy.js
          - cypress/e2e/admin/subject.cy.js
          - cypress/e2e/admin/teacher.cy.js
          - cypress/e2e/admin/attendance.cy.js
          - cypress/e2e/admin/notice.cy.js
          - cypress/e2e/admin/complaints.cy.js
          - cypress/e2e/admin/security.cy.js

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests - ${{ matrix.spec }}
        uses: cypress-io/github-action@v5
        with:
          spec: ${{ matrix.spec }}
          browser: chrome
          config: baseUrl=https://realschoolmanagementsystem.netlify.app
          record: false
          quiet: false

      - name: Upload Cypress screenshots on failure
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots-${{ matrix.spec }}
          path: frontend/cypress/screenshots
          retention-days: 5

      - name: Upload Cypress videos on failure
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-videos-${{ matrix.spec }}
          path: frontend/cypress/videos
          retention-days: 5

  all-tests-status:
    name: All Tests Status
    runs-on: ubuntu-latest
    needs: [backend-tests, frontend-build, cypress-e2e]
    if: always()

    steps:
      - name: Check test results
        run: |
          if [ "${{ needs.backend-tests.result }}" != "success" ] && [ "${{ needs.backend-tests.result }}" != "skipped" ]; then
            echo "❌ Backend tests failed or had issues"
            exit 1
          fi
          if [ "${{ needs.frontend-build.result }}" != "success" ] && [ "${{ needs.frontend-build.result }}" != "skipped" ]; then
            echo "❌ Frontend build failed"
            exit 1
          fi
          if [ "${{ needs.cypress-e2e.result }}" != "success" ] && [ "${{ needs.cypress-e2e.result }}" != "skipped" ]; then
            echo "⚠️ Some Cypress tests failed (review manually)"
          fi
          echo "✅ CI Pipeline Status Check Complete"

      - name: Comment PR with results
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const backendStatus = '${{ needs.backend-tests.result }}' === 'success' ? '✅' : '❌';
            const frontendStatus = '${{ needs.frontend-build.result }}' === 'success' ? '✅' : '❌';
            const cypressStatus = '${{ needs.cypress-e2e.result }}' === 'success' ? '✅' : '⚠️';
            
            const comment = `## CI Pipeline Results
            
            | Check | Status |
            |-------|--------|
            | Backend Tests | ${backendStatus} |
            | Frontend Build | ${frontendStatus} |
            | Cypress E2E | ${cypressStatus} |
            
            Commit: ${{ github.sha }}`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });
